#+title:  Funded Projects
#+SETUPFILE: ../org-templates/level-1.org



* Virtual Labs, Phase II
    (co-PI) 2014-2017. Sponsor: MHRD, Govt. of India. Consortium
    partners: IITs at Bombay Delhi, Guwahati Kanpur, Kharagpur,
    Roorkee, Amrita University, COE Pune, Dayalbagh University, NIT
    Surathkal. Total Budget: Rs. 69 Crores for 3 years.

* State variable approach to the model-driven development of software for reactive systems
    (PI) 2011-2013. Sponsor: Siemens India, Bangalore. Total Budget:
    Rs. 14 Lakhs.

* Distributed Model Checking
    (Co-PI) 2014-2016. Sponsor: Hitachi India Limited. Budget: 15
    Lakhs.

* Virtual Labs Phase I
    2010-2014. Sponsor: Virtual Labs consortium under the Virtual Labs
    main phase project. Budget: 3.3 Cr.

* European Commission Erasmus Mundus External Cooperation Window
    European Research and Educational Collaboration with Asia Project
    for Academic Mobility 2008-2009.[[http://www.mrtc.mdh.se/eureca/][eureca]]. Institute Coordinator for
    IIITMK. Budget: 10,000 Euro.

* ISEA
    Ministry of Information Technology, Government of
    India. Information Security Education and Awareness (ISEA)
    2006-2009. Principal Investigator at Participating Institution
    IIITM-K. Rs. 3L per annum.

* Government of Kerala
    Police Portal for Community Interaction 2004-2005. Budget
    Rs. 2,900,000. Co-investigator.


