#+title:  Students 
#+SETUPFILE: ../org-templates/level-1.org


* Current students

** Sai Gollapudi (PhD)
    Web Accessibility.

** Soumya Maddala (MS by research)
    Model based generation of software.

** Akaash Agarwall (MS Dual Degree)
    Verification of web policies.

** Adhish Singla (MS Dual Degree)
    Distributed Model Checking. Supported by Hitachi India. (Principal
    advisor: Prof. Suresh Purini)

** Arjun Sanjeev (BTech/Dual Degree)
    Formal Modelling of Design Patterns. Co-advisor: Prof. K
    Viswanath.

** Siddharth Bhat (BTech/Dual Degree)
    Programming Languages and Formal Methods.


* Past research students

** Krishna Chaitanya (MS by research, May 2016)
        Thesis title: Mitigating Web-borne Security Threats by
        Enhancing Browser Security Policies Current affiliation:
        Microsoft Hyderabad

** Ankur Goel (MS by research, Apr 2016)
        Thesis title: Specification and Modelling of Workflow
        Management Systems with State Based Access Control Current
        Affiliation: Startup in Hyderabad

** Himanshu Zade (MS by research, Apr 2015)
        Thesis title: Evolution of Mental Models of Interactive
        Machines: A Formal Approach Current affiliation: Microsoft
        Research Bangalore

** Santosh Aravind Adimoolam (MS by research Apr 2014)
        Thesis title: Automata based abstraction of interval
        assumptions and bounded input linear systems for verification
        and controller synthesis Co-advisor: Prof. K Viswanath
        Financial Support: Siemens R&D India.  Current affiliation:
        VERIMAG, France.

** Deepti Aggarwal (MS by research, Nov 2013)

        Thesis title: Exploring Crowdsourcing to PersonalizeWeb Experiences
        Co-advisor: Prof. Vasudeva Varma
        Current affiliation: Univ of Melbourne PhD programme

