#+title: Biography
#+SETUPFILE: ../org-templates/level-1.org



Venkatesh Choppella is Associate Professor of Software Engineering at the International Institute of Information Technology Hyderabad, India. He was also associated with Indian Institute of Information Technology and Management – Kerala, Trivandrum (2003-2009) and the IIIT Bangalore (2009-2010).

Venkatesh holds a PhD. degree in Computer Science from Indiana University, Bloomington, USA, and Bachelors and Masters degrees from the Indian Institutes of Technology, Kanpur and Madras, respectively. He has held research and engineering positions in Hewlett Packard, Xerox Palo Alto Research Centre, Oak Ridge National Laboratory, and the Ohio State University in the United States.

Venkatesh's current research interests are in formal methods and software architectures. In addition, he has an interest in computer science education and FOSS-based educational technology. He has published over 50 research papers and technical reports in the area of automated deduction, type systems, formal methods, compilers, and educational technology.


